apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-web
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`www.traefikdemo.com`)
    kind: Rule
    services:
      - name: traefik-dashboard-service
        namespace: kube-system
        port: 8080
