version: '3'
services:
  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "8083:8081"
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /data/nexus:/nexus-data
    container_name: nexus