apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 61.145.163.124:8084/library/test/nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 128M
            requests:
              cpu: 100m
              memory: 64M
          livenessProbe:
            httpGet:
              port: 80
              path: /index.html
            initialDelaySeconds: 5
      imagePullSecrets:
        - name: harbor-secret