version: '4'
services:
  jenkins:
    image: 61.145.163.124:8084/library/tools/jenkins:v3
    ports:
      - "8085:8080"
    restart: always
    volumes:
      - /var/lib/jenkins:/var/lib/jenkins
      - /var/log/jenkins:/var/log/jenkins
    container_name: jenkins